services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - recantonet
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  influxdb:
    image: influxdb:2.8.0
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME_FILE: /run/secrets/influxdb2-admin-username
      DOCKER_INFLUXDB_INIT_PASSWORD_FILE: /run/secrets/influxdb2-admin-password
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE: /run/secrets/influxdb2-admin-token
      DOCKER_INFLUXDB_INIT_ORG: docs
      DOCKER_INFLUXDB_INIT_BUCKET: home
    # O serviço apenas lista os secrets que vai consumir
    secrets:
      - influxdb2-admin-username
      - influxdb2-admin-password
      - influxdb2-admin-token
    volumes:
      - ./influxdb/data:/var/lib/influxdb2
      - ./influxdb/config:/etc/influxdb2
    # Healthcheck adicionado para permitir a inicialização da API
    healthcheck:
      test: ["CMD", "curl", "-sI", "http://localhost:8086/ping"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - recantonet
    restart: unless-stopped

  api:
    build:
      context: ./api
    container_name: recanto-api
    ports:
      - "${API_PORT}:8081"    
    environment:
      API_PORT: ${API_PORT}
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      MQTT_URL: tcp://${MQTT_URL}:1883
      MQTT_USERNAME: ${MQTT_USERNAME}
      MQTT_PASSWORD: ${MQTT_PASSWORD}
      MQTT_CLIENTID: ${MQTT_CLIENTID}
      MQTT_TOPIC: ${MQTT_TOPIC}
      INFLUXDB_TOKEN: ${INFLUXDB_TOKEN}
      INFLUXDB_ORG: ${INFLUXDB_ORG} 
      INFLUXDB_BUCKET: ${INFLUXDB_BUCKET}  
      INFLUXDB_URL: http://influxdb:8086
    depends_on:
      db:
        condition: service_healthy
      influxdb:
        condition: service_healthy
    networks:
      - recantonet
    restart: unless-stopped

  web:
    build:
      context: ./web
    container_name: recanto-web
    environment:
      WEB_PORT: ${WEB_PORT}
      API_URL: http://api:8081/api/
    ports:
      - "${WEB_PORT}:8080"
    depends_on:
      - api
    networks:
      - recantonet
    restart: unless-stopped

networks:
  recantonet:

# Declaração top-level obrigatória: Ensina ao Docker de onde puxar os valores
secrets:
  influxdb2-admin-username:
    environment: "INFLUXDB_USERNAME"
  influxdb2-admin-password:
    environment: "INFLUXDB_PASSWORD"
  influxdb2-admin-token:
    environment: "INFLUXDB_TOKEN"

